"""
Django settings for LibraryProject project.

Generated by 'django-admin startproject' using Django 5.1.2.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-kwdd$(_3op27y1dm!q6wfgdnr786y%t4k$%-&^6awf@sruoc(r'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = False

ALLOWED_HOSTS = ['127.0.0.1', 'yourdomain.com']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'bookshelf',
    'relationship_app',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

#Add CSP Middleware
MIDDLEWARE += [
    'csp.middleware.CSPMiddleware',
]

#Define CSP Policies in settings.py
CSP_DEFAULT_SRC = ("'self'",)
CSP_SCRIPT_SRC = ("'self'", 'https://trusted-cdn.com')
CSP_STYLE_SRC = ("'self'", 'https://trusted-cdn.com')

ROOT_URLCONF = 'LibraryProject.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'LibraryProject.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

AUTH_USER_MODEL = 'bookshelf.CustomUser'

#Add Security related setting to prevent against XSS, clickjacking and insecure content
SECURE_BROWSER_XSS_FILTER = True  # Enables browser's XSS filter
X_FRAME_OPTIONS = 'DENY'          # Prevents the site from being framed
SECURE_CONTENT_TYPE_NOSNIFF = True  # Prevents the browser from MIME-type sniffing

#Ensure Cookies are omly sent over HTTPS
CSRF_COOKIE_SECURE = True
SESSION_COOKIE_SECURE = True

#Configure Django for HTTPS Support
#Set SECURE_SSL_REDIRECT (Redirects all HTTP requests to HTTPS automatically)
SECURE_SSL_REDIRECT = True 
#Set SECURE_HSTS_SECONDS (Enforces HTTP Strict Transport Security (HSTS) for one year, ensuring browsers only access the site via HTTPS)
SECURE_HSTS_SECONDS = 31536000  # One year in seconds
#Enable HSTS Subdomain and Preload Directives (Ensures that HSTS policy applies to all subdomains and preloads the site into browsers for HTTPS-only access.)
SECURE_HSTS_INCLUDE_SUBDOMAINS = True
SECURE_HSTS_PRELOAD = True

#Enforce Secure Cookies
#Set SESSION_COOKIE_SECURE
SESSION_COOKIE_SECURE = True #Ensures session cookies are only sent over HTTPS.
#Set CSRF_COOKIE_SECURE
CSRF_COOKIE_SECURE = True #Ensures CSRF cookies are only sent over HTTPS.

#Implement Secure Headers
#Set X_FRAME_OPTIONS
X_FRAME_OPTIONS = 'DENY' #Prevents your site from being embedded in iframes, protecting against clickjacking attacks.
#set SECURE_CONTENT_TYPE_NOSNIFF
SECURE_CONTENT_TYPE_NOSNIFF = True #Prevents browsers from guessing the content type, mitigating MIME-sniffing attacks.
#Enable Browsing XSS Filtering
SECURE_BROWSER_XSS_FILTER = True #Activates the browser’s built-in XSS filter, reducing the risk of cross-site scripting attacks.
